# Generated by Django 4.1.5 on 2023-01-14 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('head_office_city', models.CharField(max_length=100)),
                ('head_office_address', models.CharField(max_length=100)),
                ('head_office_phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=255)),
                ('usd_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usd_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eur_buy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('eur_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rub_buy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rub_sell', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_number', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rates.bank')),
            ],
        ),
    ]
